
  create table "public"."faq" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "question" text not null,
    "answer" text not null,
    "category" text not null
      );


alter table "public"."faq" enable row level security;

CREATE UNIQUE INDEX faq_pkey ON public.faq USING btree (id);

alter table "public"."faq" add constraint "faq_pkey" PRIMARY KEY using index "faq_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant references on table "public"."faq" to "anon";

grant trigger on table "public"."faq" to "anon";

grant truncate on table "public"."faq" to "anon";

grant references on table "public"."faq" to "authenticated";

grant trigger on table "public"."faq" to "authenticated";

grant truncate on table "public"."faq" to "authenticated";

grant references on table "public"."faq" to "service_role";

grant trigger on table "public"."faq" to "service_role";

grant truncate on table "public"."faq" to "service_role";

grant delete on table "public"."veris_systems" to "anon";

grant insert on table "public"."veris_systems" to "anon";

grant select on table "public"."veris_systems" to "anon";

grant update on table "public"."veris_systems" to "anon";

grant delete on table "public"."veris_systems" to "authenticated";

grant insert on table "public"."veris_systems" to "authenticated";

grant select on table "public"."veris_systems" to "authenticated";

grant update on table "public"."veris_systems" to "authenticated";

grant delete on table "public"."veris_systems" to "service_role";

grant insert on table "public"."veris_systems" to "service_role";

grant select on table "public"."veris_systems" to "service_role";

grant update on table "public"."veris_systems" to "service_role";


  create policy "Enable read access for all users"
  on "public"."veris_systems"
  as permissive
  for select
  to public
using (true);



