alter table "public"."team_members" drop constraint "team_members_role_check";


  create table "public"."veris_systems" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying not null,
    "description" text default ''::text,
    "link" character varying not null,
    "is_feature" boolean not null,
    "pictures" text[]
      );


alter table "public"."veris_systems" enable row level security;

CREATE UNIQUE INDEX veris_systems_pkey ON public.veris_systems USING btree (id);

alter table "public"."veris_systems" add constraint "veris_systems_pkey" PRIMARY KEY using index "veris_systems_pkey";

alter table "public"."team_members" add constraint "team_members_role_check" CHECK ((role = ANY (ARRAY['lead'::text, 'developer'::text, 'qa'::text, 'pm'::text]))) not valid;

alter table "public"."team_members" validate constraint "team_members_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."bug_reports" to "anon";

grant insert on table "public"."bug_reports" to "anon";

grant select on table "public"."bug_reports" to "anon";

grant update on table "public"."bug_reports" to "anon";

grant delete on table "public"."bug_reports" to "authenticated";

grant insert on table "public"."bug_reports" to "authenticated";

grant select on table "public"."bug_reports" to "authenticated";

grant update on table "public"."bug_reports" to "authenticated";

grant delete on table "public"."bug_reports" to "service_role";

grant insert on table "public"."bug_reports" to "service_role";

grant select on table "public"."bug_reports" to "service_role";

grant update on table "public"."bug_reports" to "service_role";

grant delete on table "public"."site_content" to "anon";

grant insert on table "public"."site_content" to "anon";

grant select on table "public"."site_content" to "anon";

grant update on table "public"."site_content" to "anon";

grant delete on table "public"."site_content" to "authenticated";

grant insert on table "public"."site_content" to "authenticated";

grant select on table "public"."site_content" to "authenticated";

grant update on table "public"."site_content" to "authenticated";

grant delete on table "public"."site_content" to "service_role";

grant insert on table "public"."site_content" to "service_role";

grant select on table "public"."site_content" to "service_role";

grant update on table "public"."site_content" to "service_role";

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";

grant delete on table "public"."team_members" to "anon";

grant insert on table "public"."team_members" to "anon";

grant select on table "public"."team_members" to "anon";

grant update on table "public"."team_members" to "anon";

grant delete on table "public"."team_members" to "authenticated";

grant insert on table "public"."team_members" to "authenticated";

grant select on table "public"."team_members" to "authenticated";

grant update on table "public"."team_members" to "authenticated";

grant delete on table "public"."team_members" to "service_role";

grant insert on table "public"."team_members" to "service_role";

grant select on table "public"."team_members" to "service_role";

grant update on table "public"."team_members" to "service_role";

grant references on table "public"."veris_systems" to "anon";

grant trigger on table "public"."veris_systems" to "anon";

grant truncate on table "public"."veris_systems" to "anon";

grant references on table "public"."veris_systems" to "authenticated";

grant trigger on table "public"."veris_systems" to "authenticated";

grant truncate on table "public"."veris_systems" to "authenticated";

grant references on table "public"."veris_systems" to "service_role";

grant trigger on table "public"."veris_systems" to "service_role";

grant truncate on table "public"."veris_systems" to "service_role";


  create policy "Allow team update status"
  on "public"."bug_reports"
  as permissive
  for update
  to authenticated
using (true)
with check (true);


CREATE TRIGGER "notify-subscription-webhook" AFTER INSERT ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://hhgrpehnamcxrtyopwqy.supabase.co/functions/v1/notify-subscription', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZ3JwZWhuYW1jeHJ0eW9wd3F5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTQ4MDM1OSwiZXhwIjoyMTAxMDU2MzU5fQ.Yo4QsGqBqDAhvk1uo5ff8UhyG_FQMEudqVa0yzVRe5w"}', '{}', '5000');


